---
- name: "Write variables to {{ debug_dir }}/{{ inventory_hostname }}.yml"
  template:
    src: debug.yml.j2
    dest: "{{ debug_dir }}/{{ inventory_hostname }}.yml"
    owner: "{{ debug_owner }}"
    group: "{{ debug_group }}"
  check_mode: false
  tags:
    - debug

- name: Fetch the variables file
  fetch:
    src: "{{ debug_dir }}/{{ inventory_hostname }}.yml"
    dest: "{{ debug_local_dir }}/{{ inventory_hostname }}.yml"
    flat: true
  check_mode: false
  when:
    - debug_fetch is defined
    - debug_fetch
  tags:
    - debug

- name: "Debug email sent"
  mail:
    from: "root@{{ inventory_hostname }}"
    to: "{{ debug_email_address | default('root@localhost') }}"
    subject: "{{ debug_email_subject | default('Ansible variables') }}"
    charset: us-ascii
    body: "{{ debug_dir }}/{{ inventory_hostname }}.yml"
    host: localhost
    port: 25
    secure: never
  when:
    - ( debug_email is defined ) and ( debug_email == True )
    - ( debug_email_address is defined )
...
