---
- name: Generate and write debugging info
  block:

    - name: Packages present
      ansible.builtin.apt:
        pkg:
          - python3-apt

    - name: Getent passwd
      ansible.builtin.getent:
        database: passwd

    - name: Getent groups
      ansible.builtin.getent:
        database: group
        split: ':'

    - name: Getent hosts
      ansible.builtin.getent:
        database: hosts

    - name: Getent services
      ansible.builtin.getent:
        database: services

    - name: Get the apt package facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Loop through the packages to check if MariaDB is installed
      ansible.builtin.set_fact:
        debug_mariadb: true
      when: pkg.key is regex('^mariadb-server$')
      loop: "{{ ansible_facts.packages | dict2items }}"
      loop_control:
        loop_var: pkg
        label: "{{ pkg.key }}"

    - name: MariaDB facts
      block:

        - name: Stat /root/.my.cnf
          ansible.builtin.stat:
            path: /root/.my.cnf
          register: debug_mariadb_root_mycnf

        - name: Query the MariaDB version and databases using the /root/.my.cnf file
          community.mysql.mysql_info:
            filter:
              - databases
              - engines
              - global_status
              - settings
              - users
              - version
            config_file: /root/.my.cnf
            login_user: root
            login_host: localhost
            login_port: 3306
          register: debug_mariadb_info
          when: debug_mariadb_root_mycnf.stat.exists

        - name: Query the MariaDB version and databases using a socket
          community.mysql.mysql_info:
            filter:
              - databases
              - engines
              - global_status
              - settings
              - users
              - version
            return_empty_dbs: true
            login_user: root
            login_unix_socket: /run/mysqld/mysqld.sock
          register: debug_mariadb_info
          when: not debug_mariadb_root_mycnf.stat.exists

      when: ( debug_mariadb is defined ) and ( debug_mariadb )

    - name: "Write variables to {{ debug_dir }}/{{ inventory_hostname }}.yml"
      template:
        src: debug.yml.j2
        dest: "{{ debug_dir }}/{{ inventory_hostname }}.yml"
        owner: "{{ debug_owner }}"
        group: "{{ debug_group }}"
      check_mode: false

    - name: Fetch the variables file
      fetch:
        src: "{{ debug_dir }}/{{ inventory_hostname }}.yml"
        dest: "{{ debug_local_dir }}/{{ inventory_hostname }}.yml"
        flat: true
      check_mode: false
      when:
        - debug_fetch is defined
        - debug_fetch

    - name: Send the variables file by email
      block:

        - name: Slurp the variables file
          slurp:
            src: "{{ debug_dir }}/{{ inventory_hostname }}.yml"
          register: debug_variables_b64encoded

        - name: "Debug email sent"
          mail:
            from: "root@{{ inventory_hostname }}"
            to: "{{ debug_email_address | default('root@localhost') }}"
            subject: "{{ debug_email_subject | default('Ansible variables') }}"
            charset: us-ascii
            body: "{{ debug_variables_b64encoded['content'] | b64decode }}"
            host: localhost
            port: 25
            secure: never

      when:
        - ( debug_email is defined ) and ( debug_email == True )
        - ( debug_email_address is defined )

  tags:
    - debug
...
